services:
  - type: web
    name: cdhas-fastapi-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CDHAS_LOG_LEVEL
        value: INFO
      - key: CDHAS_MONGO_URI
        sync: false
      - key: CDHAS_JWT_SECRET
        generateValue: true
